module.exports = {
  parser: 'babel-eslint',
  globals: {
    app: 'readonly',
    $: 'readonly',
    jQuery: 'readonly',
    Device: 'readonly',
  },
  extends: [
    'eslint-config-airbnb-base',
    'plugin:import/errors',
    'plugin:import/warnings',
    'prettier',
  ],
  plugins: ['import', 'prettier'],
  env: {
    es6: true,
    browser: true,
  },
  rules: {
    'prettier/prettier': [
      'error',
      {
        singleQuote: true,
        trailingComma: 'all',
        bracketSpacing: false,
        jsxBracketSameLine: true,
      },
    ],
    'no-console': 0,
    'eslint-comments/no-unlimited-disable': 0,
    'eslint-comments/no-unused-disable': 0,
    'global-require': 0,
    'jsx-a11y/anchor-is-valid': 0,
    'import/no-cycle': 0,
    'no-shadow': 0,
    'import/order': 0,
    'no-nested-ternary': 0,
    'no-underscore-dangle': 0,
    'import/prefer-default-export': 0,
    'no-unused-expressions': 0,
    'no-param-reassign': 0,
    'spaced-comment': 0,
    camelcase: 0,
    'import/no-extraneous-dependencies': [
      'warn',
      {
        devDependencies: true,
        optionalDependencies: false,
        peerDependencies: false,
      },
    ],
    'import/no-unresolved': 2,
  },
};
